### ISSUE TITLE
Concat is giving correct result only once

### ISSUE THREAD

**Issue by snr-lab** [KittyMac/Sextant#8]
Run for first time
input => { "x": "1", "Y": 2 }
jsonpath => $.concat($.x,"-",$.y)

Run for second time
input => { "x": "1", "Y": 5 }
jsonpath => $.concat($.x,"-",$.y)

Expected output
First time => 1-2
Second time => 1-5

Actual output
First time => 1-2
Second time => 1-2

**Comment by KittyMac** [comment]
nice find!  fixed in v0.4.29

**Comment by snr-lab** [comment]
Thank you @KittyMac
